### ISSUE TITLE
[Bug]Unable to resolve filesystem provider with relative file path ...

### ISSUE THREAD

**Issue by JOU-amjs** [alovajs/devtools#18]
如图，非alova项目，每隔几分钟会在控制台抛出错误

![image](https://github.com/user-attachments/assets/33ba56e8-d310-4ce4-b1a8-b34cf183625d)

**Comment by czhlin** [comment]
这个是因为使用了 chokidar这个包，用文件系统监听alova.config有没有修改，可能会有兼容问题。是否考虑用定时器，定时读取一下文件内容看是否有修改。

**Comment by JOU-amjs** [comment]
原来是这样，我感觉可以考虑先判断下alova.config文件存在再监听修改

**Comment by JOU-amjs** [comment]
![image](https://github.com/user-attachments/assets/d16018b5-9dad-4045-b4bb-445c4875e8b8)
网络错误的时候还会出现这个错误
