### ISSUE TITLE
[Bug] 安装或更新 npm 依赖时，alova 插件频繁跳转错误输出界面

### ISSUE THREAD

**Issue by MeetinaXD** [alovajs/devtools#19]
## 错误描述

在启用 alova 插件的情况下，在项目内安装或更新依赖会导致错误输出。

<img width="770" alt="image" src="https://github.com/user-attachments/assets/f3bb74df-fd0c-4f94-b57c-187a514db37c">

错误产生时，vscode 会立即跳转到这个界面，影响正在进行的操作。

## 环境信息

使用的是 pnpm，其他包管理器未测试。

```
pnpm @9.3.0
node @22.4.1
vscode @1.92.0
```

**Comment by czhlin** [comment]
这个是使用了 chokidar这个包，用文件系统监听alova.config有没有修改。是否考虑用定时器，定时读取一下文件内容看是否有修改。
