### ISSUE TITLE
生成 `globals.d.ts` 时控制台报错 `Cannot read properties of undefined (reading 'enum')`

### ISSUE THREAD

**Issue by Nakus0426** [alovajs/devtools#21]
错误日志如下：
```
Cannot read properties of undefined (reading 'enum') 
Cannot read properties of undefined (reading 'title') 
Cannot read properties of undefined (reading 'enum') 
Cannot read properties of undefined (reading 'title') 
'{' expected. (1437:14)
  1435 |   success?: boolean
  1436 | } 
> 1437 | export type  = unknown 
       |              ^
  1438 | export type Result_List_6 = {
  1439 |   code?: number
  1440 |   data?: _14[] 
```
用于生成的api文件内容：
[temp.json](https://github.com/user-attachments/files/16578375/temp.json)

**Comment by Nakus0426** [comment]
大概知道原因了，api内容里的 `title` 有特殊字符 `/`，会导致找不到对应的 `Schema` 😅

**Comment by czhlin** [comment]
对，建议title中不要用“/”来命名，处理这种情况会增加查找的复杂性。
![image](https://github.com/user-attachments/assets/4a66e91f-d26d-4890-ae75-ca162b54d800)
![image](https://github.com/user-attachments/assets/37046c27-9512-4639-9746-f9d775902db5)
