### ISSUE TITLE
[Bug] file类型被处理成了string，另外似乎没有对header进行处理

### ISSUE THREAD

**Issue by cpf23333** [alovajs/devtools#25]
如图，json为swagger提供的 https://petstore.swagger.io/v2/swagger.json 
![image](https://github.com/user-attachments/assets/61fb16b2-832a-46da-bb3f-b98bc5067fe8)
![image](https://github.com/user-attachments/assets/8d2304c6-533b-44bb-adcf-e0bad5b2f359)

file类型被处理为了string，另外似乎没有对请求头的配置
请求头里 Content-Type需要为multipart/form-data
复现案例
[alova-vscode-ext-te.zip](https://github.com/user-attachments/files/16818783/alova-vscode-ext-te.zip)

**Comment by czhlin** [comment]
在正常情况下一个项目的content-type都是统一的，这个可以在beforeRequest自行处理，如果个别接口需要设置content-type也可以在index.js里的withConfig里自行处理。而上传文件这个multipart/form-data，其实是不需要任何设置的，只需要formData里包含了文件自动就会处理成这个content-type。
![image](https://github.com/user-attachments/assets/1a9c92d8-615a-4a58-acda-b0475ec7d13d)

**Comment by czhlin** [comment]
type 为file的schema我这边处理一下

**Comment by czhlin** [comment]
swagger 转成 openapi3后file类型变成了type为string,format为binary的类型
![image](https://github.com/user-attachments/assets/41d4a7ed-a03b-440a-a4c9-d72f793f0233)
