### ISSUE TITLE
使用vscode扩展生成API文档，运行项目提示找不到依赖，并且有TS语法报错

### ISSUE THREAD

**Issue by Songyuhang0818** [alovajs/devtools#28]
控制台报错如下
![image](https://github.com/user-attachments/assets/fdb1c8da-cd53-49e0-9c1e-b4641034132d)
生成的api文档
[alova.zip](https://github.com/user-attachments/files/16861506/alova.zip)
alova版本
"alova": "^3.0.15",
alova扩展版本
![image](https://github.com/user-attachments/assets/065e780b-db37-41bf-80c9-0e34e74e8ad5)

**Comment by JOU-amjs** [comment]
你的问题是因为找不到依赖导致，可以参考 https://github.com/alovajs/alova/issues/69

**Comment by Songyuhang0818** [comment]
> 你的问题是因为找不到依赖导致，可以参考 [alovajs/alova#69](https://github.com/alovajs/alova/issues/69)

![image](https://github.com/user-attachments/assets/d71e5184-3c6f-472f-8676-690af912b0ab)
安装依赖报错

**Comment by JOU-amjs** [comment]
这些包都是alova的子包，安装alova就安装了所有子包，不需要重新安装。
你的问题再通过可通过修改引入的路径解决，具体参考我提供的issue

**Comment by Songyuhang0818** [comment]
> 这些包都是alova的子包，安装alova就安装了所有子包，不需要重新安装。 你的问题再通过可通过修改引入的路径解决，具体参考我提供的issue

好的 谢谢 依赖的问题解决了 就是需要改几个@alova下的引用 

但是还有个TS的问题 麻烦再帮忙看下
![image](https://github.com/user-attachments/assets/a4a74787-0960-4f8a-b2fb-ef259eed4046)

**Comment by JOU-amjs** [comment]
我这边目前没有复现出问题，需要解决可能还希望你提供一个可复现的demo下

**Comment by Songyuhang0818** [comment]
```js
type APISofParameters<
  Tag extends string,
  Url extends string
> = Tag extends keyof Apis
  ? Url extends keyof Apis[Tag]
    ? Apis[Tag][Url] extends (...args: any) => any
      ? Parameters<Apis[Tag][Url] & ((...args: any) => any)>
      : any
    : any
  : any;
```
问了下gpt 这里Parameters<Apis[Tag][Url] & ((...args: any) => any)>加了类型断言之后 编译时候就没有提示报错了 感谢！
